version: 1 # Configuration File version

metadata:
    title: Demo # The default is the previously set name
    author: James Clef
    creator: James Clef # The default is the previously set author
    description: details
    language: zh # Language
    date: 2022-2-27 # Default is generate time
    rights: "epub by XXX" #
    cover:
        hasCover: true # boolean
        image: image/cover.jpg # path to image

content:
    -   id: copy-right
        title: Copyright
        type: text # Current available value is text image and subcontent
        path: text/copyright-infomation.md # Path to markdown file.  Cannot be null

    -   id: chapter-1
        title: Chapter 1
        type: text
        path: text/chapter01.md

    -   id: illus
        title: Copyright
        type: image
        path: image/illus.jpg

    -   id: hidden-chapter
        title: Hidden Chapter
        type: text
        path: text/hidden-chapter.md
        hiddenInContent: true # If this is true, Table of Contents will not show this chapter.

    -   id: subcontent-01
        title: Sub Content
        type: subcontent
        content:
            -   id: chapter-1
                title: Chapter 1 In Sub content
                type: text
                path: text/chapter01.md

            -   id: illus
                title: Image in subcontent
                type: image
                path: image/illus.jpg
