version: 1 # Configuration File version

name: Demo
description: details
author: James Clef

metadata:
    title: Demo # The default is the previously set name
    creator: James Clef # The default is the previously set author
    description: details
    language: zh # Language
    date: 2022-2-27 # Default is generate time
    rights: "epub by XXX" #
    cover:
        hasCover: true # boolean
        image: image/cover.jpg

content:
    copy-right:
        no-title: true
        type: text # Current available value is text and image
        path: text/copyright-infomation.md # Path to markdown file.  Cannot be null
        order: 1 # The default value is to set the order of chapter settings.
    chapter-1:
        title: Chapter 1
        type: text
        path: text/chapter01.md
        order: 2
    illus:
        no-title: true # The default vaule for image is true
        type: image
        path: image/illus.jpg
    hidden-chapter:
        title: Hidden Chapter
        type: text
        path: text/hidden-chapter.md
        hidden-in-content: true # If this is true, Table of Contents will not show this chapter.
